// src/pages/Register.vue
<template>
  <Layout>
    <div class="flex items-center justify-center min-h-[60vh]">
      <Card class="w-full max-w-md mx-4">
        <CardHeader class="space-y-1">
          <CardTitle class="text-2xl font-bold text-center">创建账号</CardTitle>
          <CardDescription class="text-center">
            开启你的 Yusi 之旅
          </CardDescription>
        </CardHeader>
        <form @submit.prevent="handleSubmit">
          <CardContent class="space-y-4">
            <div class="space-y-2">
              <label class="text-sm font-medium leading-none" for="username">
                用户名
              </label>
              <Input
                id="username"
                v-model="formData.userName"
                placeholder="请输入用户名"
                :disabled="loading"
              />
            </div>
            <div class="space-y-2">
              <label class="text-sm font-medium leading-none" for="email">
                邮箱 (可选)
              </label>
              <Input
                id="email"
                v-model="formData.email"
                type="email"
                placeholder="name@example.com"
                :disabled="loading"
              />
            </div>
            <div class="space-y-2">
              <label class="text-sm font-medium leading-none" for="password">
                密码
              </label>
              <Input
                id="password"
                v-model="formData.password"
                type="password"
                placeholder="请输入密码"
                :disabled="loading"
              />
            </div>
            <div class="space-y-2">
              <label class="text-sm font-medium leading-none" for="confirmPassword">
                确认密码
              </label>
              <Input
                id="confirmPassword"
                v-model="formData.confirmPassword"
                type="password"
                placeholder="请再次输入密码"
                :disabled="loading"
              />
            </div>
          </CardContent>
          <CardFooter class="flex flex-col gap-4">
            <Button class="w-full" type="submit" :is-loading="loading">
              注册
            </Button>
            <div class="text-sm text-center text-muted-foreground">
              已有账号？
              <RouterLink to="/login" class="text-primary hover:underline">
                立即登录
              </RouterLink>
            </div>
          </CardFooter>
        </form>
      </Card>
    </div>
  </Layout>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { authApi } from '@/lib/api'
import Layout from '@/components/Layout.vue'
import { Button, Input, Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui'

const router = useRouter()
const authStore = useAuthStore()

const loading = ref(false)
const formData = ref({
  userName: '',
  password: '',
  confirmPassword: '',
  email: ''
})

const handleSubmit = async () => {
  if (!formData.value.userName || !formData.value.password) return

  if (formData.value.password !== formData.value.confirmPassword) {
    alert('两次输入的密码不一致')
    return
  }

  loading.value = true
  try {
    const res = await authApi.register({
      userName: formData.value.userName,
      password: formData.value.password,
      email: formData.value.email
    })
    const user = res.data.data
    authStore.login(user, user.token)
    localStorage.setItem('yusi-user-id', user.userId)
    router.push('/')
  } catch (error) {
    console.error(error)
  } finally {
    loading.value = false
  }
}
</script>

// src/pages/Register.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Button, Input, Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '../components/ui'
import { authApi } from '../lib/api'
import { useAuthStore } from '../store/authStore'
import { Layout } from '../components/Layout'
import { toast } from 'sonner'

export const Register = () => {
  const navigate = useNavigate()
  const login = useAuthStore((state) => state.login)
  const [loading, setLoading] = useState(false)
  const [formData, setFormData] = useState({
    userName: '',
    password: '',
    confirmPassword: '',
    email: '',
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!formData.userName || !formData.password) return

    if (formData.password !== formData.confirmPassword) {
      toast.error('两次输入的密码不一致')
      return
    }

    setLoading(true)
    try {
      const res = await authApi.register({
        userName: formData.userName,
        password: formData.password,
        email: formData.email,
      })
      const user = res.data.data
      login(user)
      localStorage.setItem('yusi-user-id', user.userId)
      toast.success('注册成功')
      navigate('/')
    } catch (error) {
      console.error(error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Layout>
      <div className="flex items-center justify-center min-h-[60vh]">
        <Card className="w-full max-w-md mx-4">
          <CardHeader className="space-y-1">
            <CardTitle className="text-2xl font-bold text-center">创建账号</CardTitle>
            <CardDescription className="text-center">
              开启你的 Yusi 之旅
            </CardDescription>
          </CardHeader>
          <form onSubmit={handleSubmit}>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <label className="text-sm font-medium leading-none" htmlFor="username">
                  用户名
                </label>
                <Input
                  id="username"
                  placeholder="请输入用户名"
                  value={formData.userName}
                  onChange={(e) => setFormData({ ...formData, userName: e.target.value })}
                  disabled={loading}
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium leading-none" htmlFor="email">
                  邮箱 (可选)
                </label>
                <Input
                  id="email"
                  type="email"
                  placeholder="name@example.com"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  disabled={loading}
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium leading-none" htmlFor="password">
                  密码
                </label>
                <Input
                  id="password"
                  type="password"
                  placeholder="请输入密码"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  disabled={loading}
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium leading-none" htmlFor="confirmPassword">
                  确认密码
                </label>
                <Input
                  id="confirmPassword"
                  type="password"
                  placeholder="请再次输入密码"
                  value={formData.confirmPassword}
                  onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                  disabled={loading}
                />
              </div>
            </CardContent>
            <CardFooter className="flex flex-col gap-4">
              <Button className="w-full" type="submit" isLoading={loading}>
                注册
              </Button>
              <div className="text-sm text-center text-muted-foreground">
                已有账号？{' '}
                <Link to="/login" className="text-primary hover:underline">
                  立即登录
                </Link>
              </div>
            </CardFooter>
          </form>
        </Card>
      </div>
    </Layout>
  )
}
